# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Year', models.CharField(max_length=5)),
                ('Plot', models.CharField(max_length=1500)),
                ('Genre', models.CharField(max_length=250)),
                ('Imdb_rating', models.IntegerField()),
                ('Poster', models.FileField(upload_to=b'')),
                ('Path', models.CharField(max_length=100)),
            ],
        ),
    ]
