# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_movie_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Director',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Imdb_rating',
            field=models.FloatField(),
        ),
    ]
