# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_movie_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Stars',
        ),
    ]
