# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0008_auto_20160719_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Youtube_trailer',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
