# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0011_auto_20160726_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Youtube_trailer',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
